tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/science"
tap "homebrew/services"
tap "homebrew/versions"
tap "homebrew/x11"
tap "neovim/neovim"
tap "puma/puma"
cask "xquartz"
brew "ack"
brew "gettext"
brew "libffi"
brew "pcre"
brew "autoconf"
brew "autoenv"
brew "automake"
brew "gdbm"
brew "openssl"
brew "readline"
brew "sqlite"
brew "xz"
brew "python"
brew "awscli"
brew "bat"
brew "boost"
brew "freetype"
brew "fontconfig"
brew "pixman"
brew "gmp"
brew "emacs"
brew "cask"
brew "cscope"
brew "ctags"
brew "docker", link: false
brew "libyaml"
brew "docker-compose", link: false
brew "wxmac"
brew "elixir"
brew "lame"
brew "libogg"
brew "x264"
brew "xvid"
brew "ffmpeg", args: ["with-libvorbis", "with-libvpx", "with-openjpeg", "with-opus", "with-rtmpdump", "with-theora", "with-webp", "with-x265"]
brew "libvorbis"
brew "theora"
brew "ffmpeg2theora"
brew "fish"
brew "fonttools"
brew "fswatch"
brew "fzf"
brew "isl"
brew "mpfr"
brew "gcc"
brew "gdk-pixbuf"
brew "gifsicle"
brew "git"
brew "gnu-tar"
brew "libgpg-error"
brew "gnupg", link: false
brew "go"
brew "icu4c"
brew "highlight"
brew "libtool"
brew "imagemagick"
brew "intltool"
brew "jemalloc"
brew "jpegoptim"
brew "oniguruma"
brew "jq"
brew "klavaro"
brew "libao"
brew "libav"
brew "libevent"
brew "libid3tag"
brew "librsvg"
brew "libssh2"
brew "libsvg"
brew "libtermkey"
brew "libvterm"
brew "little-cms2"
brew "luajit"
brew "macvim", args: ["with-override-system-vim"]
brew "mad"
brew "mas"
brew "memcached"
brew "mongodb", restart_service: true
brew "mpg321"
brew "msgpack"
brew "mysql", restart_service: true
brew "unibilium"
brew "neovim"
brew "nmap"
brew "node"
brew "optipng"
brew "opus-tools"
brew "orc"
brew "pandoc"
brew "phantomjs"
brew "popt"
brew "postgresql@9.6", restart_service: true
brew "potrace"
brew "qt"
brew "r"
brew "rabbitmq", restart_service: true
brew "ruby-build"
brew "rbenv"
brew "reattach-to-user-namespace"
brew "redis", restart_service: true
brew "rsync"
brew "rust"
brew "scons"
brew "sdl"
brew "sdl2"
brew "shared-mime-info"
brew "smartmontools"
brew "sox"
brew "speex"
brew "ssh-copy-id"
brew "the_silver_searcher"
brew "tmux"
brew "tree"
brew "truncate"
brew "utf8proc"
brew "watch"
brew "watchman"
brew "wget"
brew "xhyve"
brew "youtube-dl"
brew "z"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
brew "heroku/brew/heroku"
brew "puma/puma/puma-dev"
cask "aerial"
cask "alfred"
cask "atom"
cask "backblaze"
cask "bartender"
cask "brave"
cask "chromedriver"
cask "dropbox"
cask "firefox"
cask "firefoxdeveloperedition"
cask "flux"
cask "focus"
cask "glueprint"
cask "gmvault"
cask "google-chrome"
cask "google-chrome-canary"
cask "gpg-suite"
cask "handbrake"
cask "harvest"
cask "iina"
cask "imagealpha"
cask "imageoptim"
cask "inkscape"
cask "iterm2"
cask "lastfm"
cask "libreoffice"
cask "macdown"
cask "messenger"
cask "michaelvillar-timer"
cask "mpv"
cask "mumble"
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "screenflow"
cask "sketch"
cask "skype"
cask "spotify"
cask "steam"
cask "subler"
cask "superduper"
cask "textexpander"
cask "textmate"
cask "tower"
cask "vagrant"
cask "vimr"
cask "virtualbox"
cask "visual-studio-code"
cask "vmware-fusion"
cask "wkhtmltopdf"
cask "xld"
cask "yakyak"
mas "1Blocker", id: 1107421413
mas "1Password 7", id: 1333542190
mas "Bear", id: 1091189122
mas "Capo", id: 696977615
mas "ColorSnapper2", id: 969418666
mas "Disk Diag", id: 672206759
mas "Evernote", id: 406056744
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "LittleSnapper", id: 403489261
mas "LocalizableStringsMerge", id: 475333727
mas "Logic Pro X", id: 634148309
mas "MainStage 3", id: 634159523
mas "Money Pro", id: 972572731
mas "Monosnap", id: 540348655
mas "Numbers", id: 409203825
mas "OmniFocus", id: 867299399
mas "OmniGraffle", id: 1142578753
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Pixelmator Pro", id: 1289583905
mas "Pocket", id: 568494494
mas "Quiver", id: 866773894
mas "Slack", id: 803453959
mas "Soulver", id: 413965349
mas "Tapes", id: 779457527
mas "The Unarchiver", id: 425424353
mas "Trello", id: 1278508951
mas "Tweetbot", id: 1384080005
mas "Xcode", id: 497799835
mas "xScope", id: 889428659
